urllist = [r"adenandanais/Babyfiles.html", r"adidas/adidas Online Shop _ adidas US.html",r"aeropostale/Sites-aeropostale-Site.html",
     r"agoda/Agoda _ Hotels in Kyoto _ Best Price Guarantee!.html",
     r"airbnb/Illinois · Stays · Airbnb.html",
     r"aldoshoes/Search - shoes _ ALDO US.html",
     r"Amazon/Amazon.com _ laptop stand.html",
     r"amextravel/American Express Hotels_ CHI - Search Results.html",
     r"artpal/Buy Vinci Art at ArtPal.html",
     r"asos/Marketplace.html",
      r"autoanything/Bumpers_AutoAnything.html",
      r"Avon/cream by Avon.html",
      r"bagborroworsteal/search _ Bag Borrow or Steal.html",
      r"barnesandnoble/comic.html",
      r"benetton/United Colors of Benetton - Official Site _ Online Shop.html",
      r"bestbuy/laptop - Best Buy.html",
      r"besttravelcoupon/BestTravelCoupon.com - Hotels in Chicago.html",
      r"bettycrocker/Search Results - BettyCrocker.com.html",
      r"bhphotovideo/nikon.html",
      r"bigbasket/Best Online Grocery Store in India. Save Big on Grocery Shopping _ bigbasket.com.html",
      r"bigstockphoto/Creativity.html",
      r"bodenusa/Search.html",
      r"bonanza/Buy executive office chair 199 items on Bonanza.html",
      r"booking/Booking.com _ Hotels in New York . Book your hotel now!.html",
      r"booksamillion/comic _ _ Booksamillion.com.html",
      r"bulq/BULQ_ Great Deals on Liquidation Inventory.html",
      r"buybuybaby/Shirt _ buybuy BABY.html",
      r"canstockphoto/Cry Stock Photo Images. 113,363 Cry royalty free pictures and photos available to download from thousands of stock photographers..html",
      r"carid/Mr. Mustang™ Bumpers - CARiD.com.html",
      r"carparts/CarParts.com - Discount Auto Body Parts Online, Cheap Aftermarket Parts.html",
      r"cartier/Search Results.html",
      r"cdw/Search Results_ Showing results for ram _ CDW.html",
      r"cheapoair/Save on Cheap Flights, Cheap Airfares, Cheap Tickets.html",
      r"cheaptickets/Chicago (and vicinity), Illinois, United States of America Hotel Search Results.html",
      r"chewy/food - Free shipping _ Chewy.html",
      r"childrensplace/Kids.html",
      r"choicehotels/Hotels in Illinois City, IL – Choice Hotels.html",
      r'coca-cola/Search results for_ BOTTLE OPENER _ Coca-Cola Store.html',
      r'concordsupplies/Isabella Management LLC DBA Concordsupplies..html',
      r'cookieskids/Cookies Kids - the Kids Department Store at Cookies Kids.html',
      r'costco/Laptops.html',
      r'costcotravel/Search - Packages _ Costco Travel.html', 
      r'countrystore/Search results for_ Red wine.html', 
      r'craigslist/norfolk_for_sale _car_ - craigslist.html', 
      r'dayuse/Dayuse_com.html', 
      r'decluttr/Products by Decluttr.html' ,
      r'departmentstoreliquidations/Department Store Liquidations. Wholesale Closeouts. Liquidation Overstock Merchandise..html', 
      r'depositphotos/Depositphotos.html' ,
      r'dickssportinggoods/Search Results.html', 
      r'discovery/SHORTS _ Discovery Store.html' ,
      r'doverpublications/Search.html', 
      r'dreamstime/Sports.html', 
      r'drupal/Found 6799 results containing the words_ pc _ Drupal.org.html', 
      r'dunhamssports/Sites-Dunhams-Site.html', 
      r'eastbay/Boots _ Eastbay.html', 
      r'ebay/headphones _ eBay.html', 
      r'ebid/car _ Items for Sale in United States.html', 
      r'ebookers/Illinois, United States of America Hotel Search Results.html', 
      r'ecrater/gloves - Filter Results.html' ,
      r'entirelypets/Entirely Pets - Search Results for food.html' ,
      r'etsy/Watch _ Etsy.html' ,
      r'expedia/Chicago, Illinois, United States of America Hotel Search Results.html' ,
      r'fandango/Movie Times and Movie Theaters in 23508 - Local Showtimes - Fandango _ Fandango.html' ,
      r'fashionphile/Shop Pre owned Designer Handbags _ Used Designer Bags _ Fashionphile.html', 
      r'fnp/Send Roses _ Buy Roses Online _ Online Roses Delivery - Ferns N Petals.html', 
      r'fragrancenet/Discount.html' ,
      r'freedigitalphotos/Eggs Pictures - Free Images of Eggs - Royalty Free Photos.html' ,
      r'freshdirect/FreshDirect - Search - onion.html' ,
      r'frys/Frys Electronics _.html' ,
      r'gamestop/mjolnir _ Search Results _ GameStop.html' ,
      r'gazelle/Buy Certified Pre-Owned iPhones, Cell Phones and iPads _ Gazelle.html', 
      r'gbyliquidations/Search results for_ Shoe.html' ,
      r'getaroom/Illingen, DE Hotels_ Cheap Rooms for Hotels in Illingen, DE at getaroom.html' ,
      r'gettyimages/1,405 Football Club Photos and Premium High Res Pictures - Getty Images.html' ,
      r'giantfood/Search Results _ Giant.html' ,
      r'glyde/Buy Used Phones for Sale the Cheaper Way - Glyde.html' ,
      r'google shopping/headphones with mic.html', 
      r'groupon/flowers _ Groupon.html', 
      r'gymboree/Kids.html' ,
      r'hallmark/Search for _birthday_ - Hallmark.html' ,
      r'hersheys/HERSHEYS _ Product Search.html' ,
      r'hilton/Hotel Search - Hilton.html' ,
      r'hipcamp/Camping Near Me _ Find The Best Campgrounds on Hipcamp.html' ,
      r'homedepot/Search Results for drill at The Home Depot.html' ,
      r'hometogo/Chicago.html' ,
      r'hopper/Hopper.html' ,
      r'hoseasons/Holiday Lodges in All Regions – Log Cabins 2020 - Hoseasons.html', 
      r'hostelworld/Hostels in Chicago » Find cheap, unique hostels » Hostelworld.html', 
      r'hotelscombined/Chicago, 11_18 — 12_8.html' ,
      r'hoteltonight/Cheap Last Minute Hotel Deals in Virginia Beach from $63 - HotelTonight.html' ,
      r'hotwire/Hotels.html' ,
     r'hrs/HRS – HOTEL RESERVATION SERVICE LTD. - Chicago (Illinois).html' ,
      r'hurb/Hotels and Packages at Illinois, United States _ Hurb.html' ,
      r'hyatt/Hyatt _ Search Results.html' ,
      r'icing/Search Page _ Icing US.html', 
      r'ihg/Select a Hotel.html' ,
      r'ikea/table - Search - IKEA.html' ,
      r'indiger/Pickles.html' ,
      r'jalan/Hokkaido Hotels - Search Result _ Jalan _ Hotel Booking Site.html', 
       r'jcpenney/shoes - JCPenney.html' ,
      r'jossandmain/Table.html' ,
      r'kayak/Book now_ Chicago, 11_26 — 11_30.html' ,
      r'kohls/Mens Shirts_ Shop Dress Shirts to Casual T Shirts and Polos for Men _ Kohls.html' ,
      r'kroger/Kroger.html' ,
      r'kushiesonline/Kushies Baby USA.html' ,
      r'laterooms/LateRooms.com _ Hotels in Manchester . Book your hotel now!.html', 
      r'lego/Search Results _ LEGO Shop.html' ,
      r'leprix/Search Results for_ bag _ LePrix.html' ,
      r'liquidation/Shirts - auctions - Liquidation.com Auctions.html' ,
      r'listia/car - Listia.com Auctions for Free Stuff.html' ,
      r'lonelyplanet/Hotels in Seville, Spain - Lonely Planet.html' ,
      r'lookfantastic/Found results for _cream_ _ Free US Shipping _ lookfantastic.html' ,
      r'maccosmetics/Search _ MAC Cosmetics - Official Site _ MAC Cosmetics - Official Site.html', 
      r'macys/Mens Shirts - Macys.html' ,
      r'marriott/Search Results.html' ,
      r'marykay/Mary Kay Search Results.html' ,
      r'mercari/shoes _ Mercari.html' ,
      r'metmuseum/Art.html' ,
      r'microcenter/Laptops_Notebooks _ Micro Center.html', 
      r'momondo/Illinois, 11_8 — 11_9.html' ,
      r'mrandmrssmith/Boutique.html' ,
      r'mynavyexchange/Search Results _ Shop Your Navy Exchange - Official Site.html' ,
      r'nba/store.nba.com.html' ,
      r'neutrogena/Search Results _ Neutrogena®.html' ,
      r'newbalance/shoes Search Results - New Balance.html' ,
      r'nflshop/NFL Gear - NFLShop.com.html' ,
      r'nhc/Search results for _Vitamin_.html' ,
      r'nike/Products. Nike.com.html' ,
      r'officedepot/table - Office Depot.html' ,
      r'officesupplynow/OfficeSupplyNow.com - The Trimmer Place.html' ,
      r'oncewed/Search.html' ,
      r'onetravel/Onetravel _ Hotels in Chicago . Book your hotel now!.html',
      r'onlinesports/Search results for_ball_OnlineSports.com.html' ,
      r'oodle/_car_ _ Cars for Sale in Norfolk, Virginia _ Used Cars on Oodle Classifieds.html', 
      r'orbitz/Illinois, United States of America Hotel Search Results.html' ,
      r'origins/Endeca - Search + Results _ Origins.html' ,
      r'overstock/Kitchen.html' ,
      r'oyorooms/Hotels.html' ,
      r'petco/Search Results.html' ,
      r'petsmart/Search Results _ PetSmart.html' ,
      r'petsupplies/Supplies.html' ,
      r'petsuppliesplus/Search.html' ,
      r'poppin/Search Results _ Poppin.html' ,
      r'poshmark/Nike for Women - Poshmark.html' ,
      r'powells/Search Results - Powells Books.html' ,
      r'premierinn/Search.html' ,
      r'preownedweddingdresses/Search.html' ,
      r'priceline/Chicago Hotels_ 11_05 - 11_06 _ Priceline.html' ,
      r'pruvo/Pruvo – Book your hotel - Hotels in Chicago.html' ,
      r'puma/Search Result_ shoes.html' ,
      r'redbubble/Face Masks _ Redbubble.html' ,
      r'reebok/Reebok Online Shop _ Reebok US.html' ,
      r'riteaid/riteaid.html' ,
      r'roomertravel/Chicago Hotel Deals, Roomer.html' ,
      r'rubylane/Rings Jewelry _ Ruby Lane.html' ,
      r'saatchiart/Landscape Photography For Sale _ Saatchi Art.html' ,
      r'safeway/Search Results _ Safeway.html' ,
      r'sears/Laptop.html' ,
      r'sebamedusa/Dermatologist Recommended Sensitive Skin Care Solutions.html' ,
      r'secondsale/Best Books about art of war.html' ,
      r'sellcell/Sell Apple iPhone 12 Pro _ Trade In iPhone 12 Pro.html' ,
      r'sephora/Search _ Sephora.html' ,
      r'shopbeergear/Shop Beer Gear.html' ,
      r'shopbop/jean _ SHOPBOP.html' ,
      r'shopdisney/shopDisney _ shopDisney.html' ,
      r'shopgoodwill/Search Results_ shirt - shopgoodwill.com.html', 
      r'shopjustice/Justice _ Justice.html' ,
      r'shopthesalvationarmy/ShopTheSalvationArmy.html' ,
      r'shopzilla/Shopzilla - Jacket.html' ,
      r'shutterstock/Sports.html' ,
      r'sisley/Sisley - Official Site _ Online Shop.html' ,
      r'skyscanner/Cheap domestic flights from Norfolk.html' ,
      r'spalding/Sporting.html' ,
      r'sportsdirect/Search Results.html' ,
      r'sportsunlimitedinc/Results for boots.html' ,
      r'staples/Shop.html' ,
      r'swansonvitamins/Vitamins and Supplements, Natural Health Products, Organic Foods - Swanson Health Products.html', 
      r'sykescottages/Search and Find a Cottage in UK and Ireland _ Sykes Cottages.html', 
      r'szallas/Balaton accommodations - 3885 offers - Revngo.com.html' ,
      r'tabasco/You searched for mexican _TABASCOBrand.html' ,
      r'tablethotels/Boutique.html' ,
      r'target/Tv _ Target.html' ,
      r'tenthousandvillages/Search results for_table.html' ,
      r'thellegance/Online shopping for Digital Watches with free worldwide shipping.html', 
      r'thenewyorkdogshop/The New York Dog Shop.html', 
      r'thomascook/Thomas Cook.html' ,
      r'thredup/Womens Clothing.html' ,
      r'thriftbooks/Browse.html' ,
      r'tias/Search - comic - TIAS.com.html' ,
      r'tigerdirect/Laptop.html' ,
      r't-mobile/search.html' ,
      r'toofaced/Search _ TooFaced.html' ,
      r'totalwine/Total.html' ,
      r'tradesy/Womens Shoes.html' ,
      r'travelocity/Illinois, United States of America Hotel Search Results.html' ,
      r'travelzoo/Hotels + New York City, NY + All Dates _ Travelzoo.html' ,
      r'tripadvisor/Tripadvisor.html' ,
      r'trivago/Chicago.html' ,
      r'usps/Shipping Supplies _ USPS.com.html' ,
      r'veneretravel/Venere Travel.html' ,
      r'verizon/Search Results for iphone at Verizon.html' ,
      r'vitaminshoppe/Search.html' ,
      r'vitaminworld/Shop Vitamin B _ Vitamin World.html' ,
      r'vrbo/Chicago pet friendly vacation rentals _ Vrbo.com.html' ,
      r'walgreens/mask _ Walgreens.html' ,
      r'walmart/laptop computer - Walmart.com.html' ,
      r'wayfair/Wayfair.html' ,
      r'wotif/Chicago (and vicinity), Illinois, United States of America Hotel Search Results.html' ,
      r'wyndhamhotels/Search.html' ]